micronaut:
  application:
    name: micronautdemo
  server:
    cors:
      enabled: true
---
#logger:
#  levels:
#    io.micronaut: DEBUG
---
micronaut:
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:BbLffiYSlIr2rXUYd+3KmFT1O5eYmSWzq0T6Jlog42Q}"'
---
micronaut:
  security:
    token:
      jwt:
        generator:
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:f4glHenFWz3yP1pVDTlhWwQxoT1B1lUsX0dJwzofpPE}"'
---
app:
  dummy-users:
  - id: '1'
    username: 'admin1@test'
    password: "${TEST_USER_PASSWD}"
    roles:
      - 'ROLE_ADMIN'
      - 'ROLE_USER'
  - id: '2'
    username: 'user1@test'
    password: "${TEST_USER_PASSWD}"
    roles:
      - 'ROLE_USER'
  - id: '3'
    username: 'user2@test'
    password: "${TEST_USER_PASSWD}"
    roles:
      - 'ROLE_USER'

---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2